robot_name: bimanual_xarm

# Detector used to teleoperate the robot
detector:
  _target_: openteach.components.detector.oculusbimanual.OculusVRTwoHandDetector
  host: ${host_address}
  oculus_right_port: ${oculus_reciever_port}
  oculus_left_port: ${left_hand_receiver_port}
  keypoint_pub_port: ${keypoint_port}
  button_port: ${resolution_button_port}
  button_publish_port: ${resolution_button_publish_port}

# Transformation classes used to transform the keypoints
transforms:
  - 
    _target_: openteach.components.detector.keypoint_transform.TransformHandPositionCoords
    host: ${host_address}
    keypoint_port: ${keypoint_port}
    transformation_port: ${transformed_position_keypoint_port}
    moving_average_limit: 1

  - 
    _target_: openteach.components.detector.left_keypoint_transform.TransformLeftHandPositionCoords
    host: ${host_address}
    keypoint_port: ${keypoint_port}
    transformation_port: ${transformed_position_left_keypoint_port}
    moving_average_limit: 1

# Visualizers used to visualize the keypoints stream
visualizers:
  -
    _target_: beavr.components.visualizers.visualizer_2d.Hand2DVisualizer
    host: ${host_address}
    transformed_keypoint_port: ${keypoint_transform_port}
    oculus_feedback_port: ${oculus_graph_port}
    display_plot: ${visualize_right_2d}

robots:
  -
    _target_: beavr.interfaces.xarm7_robot.XArm7Robot
    host: ${host_address}
    # --- Parameters for the Robot Interface itself ---
    robot_ip: ${right_xarm_ip}
    is_right_arm: True # Used by XArm7Robot to determine its name/topic
    endeff_publish_port: 10010 # General purpose publisher port
    endeff_subscribe_port: 10009 # Command subscriber port
    joint_subscribe_port: 10029 # Command subscriber port
    reset_subscribe_port: 10009 # Command subscriber port

    # --- Parameters for State Dictionary Publishing (Used by Robot Interface AND Collector) ---
    state_publish_port: 10011 # <<< NEW/CONFIRMED: Dedicated port for state dict publishing

    # --- Parameters specifically for the Recorders (Used ONLY by Collector) ---
    recorder_config:
      robot_identifier: "right_xarm7" # <<< NEW: Unique name for recorder filenames/logs
      # expected_zmq_topic: "right_xarm7" # Optional: Explicit topic. We'll derive it for XArm7.
      recorded_data: # <<< MOVED/NEW: List of keys to record for THIS robot
        - joint_states
        - xarm_cartesian_states # Make sure this matches the key in the robot's published dict
        - commanded_cartesian_state # Make sure this matches the key in the robot's published dict
        # Add other keys published by XArm7Robot.publish_current_state here
  - 
    _target_: beavr.interfaces.xarm7_robot.XArm7Robot
    host: ${host_address}
    endeff_publish_port: 10012
    endeff_subscribe_port: 10011
    joint_subscribe_port: 10030
    reset_subscribe_port: 10011
    robot_ip: ${left_xarm_ip}
    is_right_arm: False

    # --- Parameters specifically for the Recorders (Used ONLY by Collector) ---
    recorder_config:
      robot_identifier: "left_xarm7" # <<< NEW: Unique name for recorder filenames/logs
      # expected_zmq_topic: "right_xarm7" # Optional: Explicit topic. We'll derive it for XArm7.
      recorded_data: # <<< MOVED/NEW: List of keys to record for THIS robot
        - joint_states
        - xarm_cartesian_states # Make sure this matches the key in the robot's published dict
        - commanded_cartesian_state # Make sure this matches the key in the robot's published dict
        # Add other keys published by XArm7Robot.publish_current_state here

operators:
  - 
    _target_: beavr.components.operators.xarm7_right.XArm7RightOperator
    host: ${host_address}
    transformed_keypoints_port: ${keypoint_transform_port}
    stream_configs:
      host: ${host_address}
      port: ${sim_image_port}
    stream_oculus: true
    endeff_publish_port: 10009
    endeff_subscribe_port: 10010
    moving_average_limit: 1
    arm_resolution_port: ${unified_data_port}
    use_filter: False
    teleoperation_reset_port: ${unified_data_port}
    logging_config:
      enabled: False
      log_dir: "logs"
      log_poses: True
      log_prefix: "xarm_right"
  
  - 
    _target_: beavr.components.operators.xarm7_left.XArm7LeftOperator
    host: ${host_address}
    transformed_keypoints_port: ${left_keypoint_transform_port}
    stream_configs:
      host: ${host_address}
      port: ${sim_image_port}
    stream_oculus: true
    endeff_publish_port: 10011
    endeff_subscribe_port: 10012
    moving_average_limit: 1
    arm_resolution_port: ${unified_data_port}
    use_filter: False
    teleoperation_reset_port: ${unified_data_port}
    logging_config:
      enabled: False
      log_dir: "logs"
      log_poses: True
      log_prefix: "xarm_left"