robot_name: leap_hand

# Detection from the oculus
detector:
  _target_: beavr.components.detector.oculus.OculusVRHandDetector
  host: ${host_address}
  oculus_port: ${oculus_receiver_port}
  unified_pub_port: ${unified_data_port}
  button_port: ${resolution_button_port}
  teleop_reset_port: ${teleop_reset_port}

# Transforming the keypoints from the oculus
transforms:
  - 
    _target_: beavr.components.detector.keypoint_transform.TransformHandPositionCoords
    host: ${host_address}
    keypoint_port: ${unified_data_port}
    transformation_port: ${keypoint_transform_port}
    moving_average_limit: 1

# Visualizers used to visualize the keypoints stream
visualizers:
  - 
    _target_: beavr.components.visualizers.visualizer_2d.Hand2DVisualizer
    host: ${host_address}
    transformed_keypoint_port: ${keypoint_transform_port}
    oculus_feedback_port: ${oculus_graph_port}
    display_plot: ${visualize_right_2d}

operators:
  - 
    _target_: beavr.components.operators.leap_pybullet.LeapHandOperator
    host: ${host_address}
    transformed_keypoints_port: ${keypoint_transform_port}
    joint_angle_subscribe_port: ${joint_publisher_port}
    joint_angle_publish_port: ${cartesian_command_publisher_port}
    reset_publish_port: ${teleop_reset_publish_port}
    finger_configs:
      freeze_index: false
      freeze_middle: false
      freeze_ring: false
      freeze_thumb: false
      no_index: false
      no_middle: false 
      no_ring: false
      no_thumb: false
      three_dim: true
    logging_config:
      enabled: false
      log_dir: "logs"
      log_poses: true
      log_prefix: "leap"

robots:
  -
    _target_: beavr.interfaces.leap_robot.LeapHandRobot
    host: ${host_address}
    joint_angle_subscribe_port: ${cartesian_command_publisher_port}
    joint_angle_publish_port: ${joint_publisher_port}
    reset_subscribe_port: ${teleop_reset_publish_port}
    simulation_mode: false

recorded_data:
  - 
    - joint_states
    - commanded_joint_states