# configs/robot/beavr_xarm_adapter.yaml
_target_: beavr.common.robot_devices.robots.configs.BeavrRobotAdapterConfig

# --- ZMQ Connection Settings ---
# These MUST match the XArm7Robot publisher from xarm7_right.yaml
robot_state_host: "localhost" # Or the correct host of the publisher
robot_state_port: 10011
robot_state_topic: "right_xarm7"

# --- State Mapping (observation.state <- joint_states) ---
actual_state_input_key: "joint_states"
actual_state_payload_key: "joint_position"

# --- Action Mapping (action <- commanded_cartesian_state) ---
command_input_key: "commanded_cartesian_state"
command_payload_key: "commanded_cartesian_position"

# --- IK Configuration ---
# Tells the adapter to convert the Cartesian action to joint angles
use_cartesian_action: True
# IP needed for the internal IK solver
xarm_ip: ${right_xarm_ip} # Assumes this is defined elsewhere in your main config

# --- Data Type Configuration ---
# Assumes the joint states from the ZMQ topic are in degrees
input_angles_are_degrees: True

# --- Camera Configuration ---
# Add your camera configs here as the adapter also handles them
cameras:
  front_cam:
    _target_: beavr.common.robot_devices.cameras.configs.OpenCVCameraConfig
    camera_index: 4
    fps: 30
    width: 640
    height: 480
    rotation: 0  # Degrees, if camera needs rotation
    mock: false  # Set to true for testing
  # wrist_cam:  # Optional second camera
  #   _target_: beavr.common.robot_devices.cameras.configs.OpenCVCameraConfig
  #   camera_index: 1
  #   fps: 30
  #   width: 640
  #   height: 480
  #   rotation: 0
  #   mock: false