robot_name: xarm_pybullet

# Detection from the oculus
detector:
  _target_: beavr.src.components.detector.oculus.OculusVRHandDetector
  host: ${host_address}
  oculus_port: ${oculus_reciever_port}
  keypoint_pub_port: ${keypoint_port}
  button_port: ${resolution_button_port}
  button_publish_port: ${resolution_button_publish_port}
  teleop_reset_port: ${teleop_reset_port}
  teleop_reset_publish_port: ${teleop_reset_publish_port}

# Transform the keypoints
transforms:
  - 
    _target_: beavr.src.components.detector.keypoint_transform.TransformHandPositionCoords
    host: ${host_address}
    keypoint_port: ${keypoint_port}
    transformation_port: ${transformed_position_keypoint_port}
    moving_average_limit: 1

# Visualizers (optional)
visualizers:
  - 
    _target_: beavr.src.components.visualizers.visualizer_2d.Hand2DVisualizer
    host: ${host_address}
    transformed_keypoint_port: ${transformed_position_keypoint_port}
    oculus_feedback_port: ${oculus_graph_port}
    display_plot: ${visualize_right_2d}

# XArm PyBullet operator
operators:
  - 
    _target_: beavr.src.components.operators.xarm_pybullet_sim.XArmPyBulletOperator
    host: ${host_address}
    transformed_keypoints_port: ${transformed_position_keypoint_port}
    finger_configs:
      freeze_index: false
      freeze_middle: false
      freeze_ring: false
      freeze_thumb: false
      no_index: false
      no_middle: false
      no_ring: false
      no_thumb: false
      three_dim: true
    stream_configs:
      host: ${host_address}
      port: ${sim_image_port}
    stream_oculus: true
    jointanglepublishport: 10013
    jointanglesubscribeport: 10012
    endeff_publish_port: 10010
    endeffpossubscribeport: 10009
    moving_average_limit: 1
    arm_resolution_port: ${resolution_button_publish_port} 
    use_filter: False
    teleoperation_reset_port: ${teleop_reset_publish_port}
    logging_config:
      enabled: True
      log_dir: "logs"
      log_poses: True
      log_prefix: "xarm"

# XArm PyBullet environment
environment:
  - 
    _target_: beavr.src.components.environment.xarm_env.XArmEnv
    host: ${host_address}
    camport: ${sim_image_port}
    timestamppublisherport: 10008
    endeff_publish_port: 10009
    endeffpossubscribeport: 10010
    robotposepublishport: 11111
    stream_oculus: true
    sim_frequency: 30
    control_mode: 'absolute'
    logging_config:
      enabled: True
      print_joint_changes: False
      print_target_analysis: False
      print_workspace_warnings: True

# Recording configuration
recorded_data:
  - 
    - cartesian_states
    - commanded_cartesian_states

# Add port_configs section
port_configs:
  -
    robot: 'xarm_pybullet'
    host: ${host_address}
    port: ${sim_image_port}
    jointanglepublishport: 10012
    jointanglesubscribeport: 10013
    timestampssubscribeport: 10008
    actualjointanglesubscribeport: 10011   
    endeffpossubscribeport: 10010
    endeff_publish_port: 10009