host_address: '10.29.155.27'

left_xarm_ip: '192.168.86.237'
right_xarm_ip: '192.168.1.197'

# Consolidated ports - one publisher per process
keypoint_stream_port: 8088     # All keypoint data from VR/Oculus
control_stream_port: 8089      # All control signals (buttons, resets)
robot_state_port: 8090         # Robot state information
robot_command_port: 8091       # Robot commands

# Input ports (PULL sockets - these remain separate)
oculus_receiver_port: 8087     # Raw data from Oculus
resolution_button_port: 8095   # Button input
teleop_reset_port: 8100        # Reset signal input

# Other ports (unchanged)
cam_port_offset: 10005
oculus_graph_port: 15001
deployment_port: 10000
sim_image_port: 10005
fish_eye_cam_port_offset: 10010

pre_action_thumb_ee_position_port: 8091
post_action_thumb_ee_position_port: 8092

gripper_publish_port_right: 8108
gripper_publish_port_left: 8115

cartesian_publisher_port: 8118
joint_publisher_port: 8119
cartesian_command_publisher_port: 8120

cartesian_publisher_port_left: 8116
joint_publisher_port_left: 8117
cartesian_command_publisher_port_left: 8121

resolution_button_publish_port: 8093
teleop_reset_publish_port: 8102

# New ports we added
unified_data_port: 8088     # All data from oculus.py 
keypoint_transform_port: 8092  # Transformed keypoints


